{
 "title": "Consommation énergie",
 "time": { "from": "now-3w", "to": "now" },
 "panels": [
  {
   "title": "Consommation par tranche 30 min",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__CDC_SOUTIRAGE\")\n  |> filter(fn: (r) => r[\"PRM\"] == \"15266280650801\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")\n\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Synthèse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Proportion du type d'énergie consommé sur la période",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__ENERGIE_SOUTIRAGE\" or r[\"_measurement\"] == \"GRDF__CONSOMMATION\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")"
    }
   ]
  },
  {
   "title": "Dernière consommation électricité",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__ENERGIE_SOUTIRAGE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")"
    }
   ]
  },
  {
   "title": "Dernière puissance apparente maximale",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__PMAX_SOUTIRAGE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kVA\")"
    }
   ]
  },
  {
   "title": "Consommation électrique",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Consommation électricité",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__ENERGIE_SOUTIRAGE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kWh\")"
    }
   ]
  },
  {
   "title": "Courbe de charge électricité deux derniers jours",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"maconso\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ENEDIS__CDC_SOUTIRAGE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"kW\")"
    }
   ]
  }
 ]
}